version: "3.9"

services:
  web:
    build:
      context: .
    container_name: myproject
    ports:
      - "8003:8003"
      - "4567:4567"
    volumes:
      - ./:/app:cached
    working_dir: /app
    command: >
      python -m debugpy --listen 0.0.0.0:4567 manage.py runserver 0.0.0.0:8003
    depends_on:
      - db
    environment:
      DB_NAME: bookrental
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 9876

  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    ports:
      - "7771:9876"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: bookrental
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    command: postgres -p 9876

  # เพิ่ม nginx service
  nginx:
    image: nginx:alpine
    container_name: bookrental-nginx
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - web
    restart: always

volumes:
  postgres_data: