# Generated by Django 5.2.1 on 2025-08-15 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='available_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
